export const SET_TOP_PRODUCTS = "SET_TOP_PRODUCTS"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
